### ISSUE TITLE
Any way to restrict iOS to only 5s?

### ISSUE THREAD

**Issue by jamesmontemagno** [MikeCodesDotNet/My-StepCounter#5]
https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/App-RelatedResources/App-RelatedResources.html#//apple_ref/doc/uid/TP40007072-CH6-SW10  

I think we can change it in the info.plist?

**Comment by MikeCodesDotNET** [comment]
Think we can safely say most people are now sporting a device capable of running the app.
